<?php
	@include("Lib1/_common_path.php");
	@include("Lib1/_common.php");
	@include("../../Lib1/_common_path.php");
	@include("../../Lib1/_common.php");
	@include("../Lib1/_common_path.php");
	@include("../Lib1/_common.php");
	@include("../../../Lib1/_common_path.php");
	@include("../../../Lib1/_common.php");
?>