<?php
	@include("Lib/_common_path.php");
	@include("Lib/_common.php");
	@include("../../Lib/_common_path.php");
	@include("../../Lib/_common.php");
	@include("../Lib/_common_path.php");
	@include("../Lib/_common.php");
	@include("../../../Lib/_common_path.php");
	@include("../../../Lib/_common.php");
?>